Revert " fs/dyn_sync_cntrl: dynamic sync control"
This reverts commit f83fe4dec05f4e863094e37f9e7c60e57a57eb89.

/home/john/jellybean/kernel/samsung/d2/fs/dyn_sync_cntrl.c: In function 'dyn_fsync_early_suspend':
/home/john/jellybean/kernel/samsung/d2/fs/dyn_sync_cntrl.c:102:3: error: too few arguments to function 'wakeup_flusher_threads'
/home/john/jellybean/kernel/samsung/d2/include/linux/writeback.h:96:6: note: declared here
make[3]: *** [fs/dyn_sync_cntrl.o] Error 1
make[2]: *** [fs] Error 2
make[2]: *** Waiting for unfinished jobs....